### ISSUE TITLE
Make a MARI Script update workflow

### ISSUE THREAD

**Issue by Pasarus** [interactivereduction/autoreduction-scripts#4]
The MARI script should be automatically updated when changes are made to the script in the Mantid Script repository and a PR should be opened in this repo.

Ideally, this should be achieved in a manner that allows it to be extensible and reused.

**Comment by keiranjprice101** [comment]
It would also be nice if we can setup an action to trigger the CI for the IR-API when this PR is opened

**Comment by keiranjprice101** [comment]
Done
